### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by ijskor** [CodeForFoco/solar-scorecard#40]
Let's create a widget that can be easily added to other websites.

**Comment by deidyomega** [comment]
Like old school iframe, or are you thinking an embeddable script that onload injects the <whatever> into the page?

**Comment by abettermap** [comment]
Embeddable script like FB's SDK and Google Analytics? Seems nicer than an iframe, but what would it take to implement that?

**Comment by deidyomega** [comment]
From the non-technical answer:

You'd create a `<div id="embeded-solar"></div>`

that'd be the place the file would use, then you'd use a `remote` script tag `<script src=solar.heroku.com/embeded.js></script>`

Internal to that embedded.js you'd just make sure it references the right tag.

The real trick here is, you really need to minimize the outside requirements and make sure you listen for them to have loaded prior to doing whatever your main script's function is.

Overall, this process works well, just usually a bit heavy, since all the CSS and HTML have to be packaged inside that single js file.

If you want a proof of concept, just let me know, and I'll create something for you guys.

**Comment by abettermap** [comment]
Ian and I are clarifying "widget" a bit: a simple, non-interactive visual display of one or two solar-related Fort Collins metrics that would be accessible via the Scorecard website. The widget would include:

1. Static (but dynamically generated) graphic of the metric/s
1. Text blurb describing what the graphic shows
1. **Learn More** link/button pointed at Scorecard website. 

Widget would potentially be used in the sidebar of the [FC renewables page](https://www.fcgov.com/utilities/residential/renewables).

So, could we use an iframe then?

**Comment by deidyomega** [comment]
Either option would work.

iframe --> you host an html page that does whatever you need it to do.  Easier to do but not as common nowadays.  (iframes aren't cool anymore)
js --> You host a JS file, that generates the HTML to do whatever you need it to do.

At scale, the JS solution requires fewer server resources, but I doubt the # of users will ever be large enough to even worry about.

**Comment by ijskor** [comment]
Let's go with iframe for now then. Can someone layout the steps for me so I can start to create issues?

**Comment by abettermap** [comment]
@deidyomega- Would we make a separate standalone page and point the iframe to that? As opposed to pointing it at the full site, since that would obviously have things we don't want in a widget.
